# Generated by Django 4.2.3 on 2023-07-24 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('s3Uri', models.URLField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
