# Generated by Django 4.2.3 on 2023-07-25 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0003_file_shared_with_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='shared_with_users',
        ),
        migrations.AddField(
            model_name='file',
            name='shared',
            field=models.ManyToManyField(blank=True, related_name='shared', to=settings.AUTH_USER_MODEL),
        ),
    ]
